<?php
include_once($_SERVER['DOCUMENT_ROOT'].'/hospital2/classes/doctor.php');
$resultString='';
if($_SERVER['REQUEST_METHOD']=='POST'){
    if(session_status()==PHP_SESSION_ACTIVE){
    }else{
        session_start();
    }
    $name=$_POST['name'];
    $contact=$_POST['contact'];
    $email=$_POST['email'];
    $gender=$_POST['gender'];
    $age=$_POST['age'];
    $medHistory=$_POST['medHistory'];   
    $result = Doctor::AddPatient($_SESSION['doctor_id'],$name,$contact,$email,$gender,$age,$medHistory);
    if($result){
        $resultString='1';
    }else{
        $resultString='0';
    }
}